#:schema node_modules/wrangler/config-schema.json

name = "xrontrix-portfolio"
compatibility_date = "2024-09-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "PORTFOLIO_STORAGE"
id = "46b9c8409489410b92d3163f40af3bc6"