import type { ReactNode } from "react";

import "@/styles/questions.css";

/**
 * Terminal commands.
 * @type {object} questions as string and answers as React.ReactNode.
 */
export const questions: {
  question: string;
  command: string;
  answer: ReactNode;
}[] = [
  {
    question: "Who/What is Xron Trix?!",
    command: "whois xrontrix --verbose",
    answer: (
      <article className="qn_answer">
        <p>
          You probably guessed it! It&apos;s not my real name. I always wanted
          to name myself something unique :)
        </p>
        <p>
          I loved the series <span>Ben 10</span> from Cartoon Network. So, the{" "}
          <span>&quot;Trix&quot;</span> was taken from the watch name
          &quot;Omnitrix&quot;.
        </p>
        <p>
          Then <span>&quot;Xron&quot;</span> was added to the front to make it
          sound more unique, generated by my brain.
        </p>
        <p>Though &quot;X&quot; was inspired by Elon Musk :D</p>
      </article>
    ),
  },
  {
    question: "What I actually do?",
    command: "man xrontrix",
    answer: (
      <article className="qn_answer">
        <p>I actually do a lot more than a &quot;front-end developer&quot;.</p>
        <p>
          I was more interested and curious in <span>backends</span>,{" "}
          <span>cloud</span> and logic building. But suddenly I also became good
          at frontend development. So, I landed my <span>first job</span> as a
          front-end developer.
        </p>
        <p>
          Along with frontend, I have worked on multiple backends and full-stack
          applications. Most of them are in <span>NodeJs</span>,{" "}
          <span>MongoDB</span> or <span>SQL</span>.
        </p>
        <p>
          But, my favourite backend stack is <span>Go</span> with{" "}
          <span>PostgreSQl</span>. For frontend, I use <span>Next.js</span>,{" "}
          <span>TypeScript</span> and <span>TailwindCSS</span>
        </p>
        <p>
          Btw, this portfolio is built with Next.js and TailwindCSS, it&apos;s
          using <span>Cloudflare serverless Pages</span> and{" "}
          <span>KV database</span> :D
        </p>
      </article>
    ),
  },
  {
    question: "Skills? Experience?",
    command: "info xrontrix --format=table",
    answer: (
      <article className="qn_answer">
        {/* Basics table */}
        <h4>Basics</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>HTML, CSS</td>
              <td>5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Bash</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Git</td>
              <td>3.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>C, C++, Python</td>
              <td>5 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        {/* Front-end table */}
        <h4>Front-end</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>JavaScript (ES6+)</td>
              <td>4 Yr+ Experience</td>
            </tr>
            <tr>
              <td>React</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Next.js</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>TypeScript</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>TailwindCSS</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        {/* Back-end table */}
        <h4>Back-end</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>NodeJs</td>
              <td>3 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Go</td>
              <td>1 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Cloudflare Workers</td>
              <td>3 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        <h4>Database</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>PostgreSQL</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>MongoDB</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>SQL</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Cloudflare KV, D1 (SQLite)</td>
              <td>2 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        {/* Other table */}
        <h4>Other Essentials</h4>

        <table>
          <thead>
            <tr>
              <th>Skill</th>
              <th>Progress</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Data structure & Algorithms</td>
              <td>Leetcode 80+ Solutions</td>
            </tr>
            <tr>
              <td>Computer Network</td>
              <td>Intermediate</td>
            </tr>
            <tr>
              <td>Linux</td>
              <td>Debian, Arch (3+ Yr+ Experience)</td>
            </tr>
            <tr>
              <td>Cryptography, Encryption</td>
              <td>In Progress</td>
            </tr>
            <tr>
              <td>DevOps</td>
              <td>In Progress</td>
            </tr>
          </tbody>
        </table>
      </article>
    ),
  },
  {
    question: "Where I'm from?",
    command: "whereis xrontrix",
    answer: (
      <article className="qn_answer">
        <p>
          XronTrix is from{" "}
          <a
            rel="noreferrer"
            target="_blank"
            href="https://ben10.fandom.com/wiki/Galvan_Prime_(Classic)"
          >
            Galvan Prime
          </a>
          . He was created by{" "}
          <a
            rel="noreferrer"
            target="_blank"
            href="https://ben10.fandom.com/wiki/Azmuth_(Classic)"
          >
            Azmuth
          </a>
          .
        </p>
        <p>
          He is an advanced humanoid with a unique ability to teleport. He
          travels the galaxy in search of new worlds to explore.
        </p>

        <p>Just Kidding :D</p>
      </article>
    ),
  },
  {
    question: "What is my current role?",
    command: "which role",
    answer: (
      <article className="qn_answer">
        <p>
          Currently, I&apos;m a front-end developer intern at{" "}
          <a href="https://in.linkedin.com/company/pegnamindiapvtltd">Pegman</a>{" "}
          ;)
        </p>
      </article>
    ),
  },
  {
    question: "Strengths and weaknesses?",
    command: "describe --strengths --weakness",
    answer: (
      <article className="qn_answer">
        <p>My strength is me, myself. I am a resolute.</p>
        <p>
          I was a back bencher till my high school and never really cared about
          anything. Now when I look back, I feel proud of me for coming this far
          :)
        </p>
        <p>
          I believe that I can do anything I set my mind to. Self believe is my
          biggest strength
        </p>
        <p>
          My weaknesses include my little short term memory and a little
          nervousness in public speaking. Though I am working on it :D
        </p>
      </article>
    ),
  },
  {
    question: "Favorite technologies?",
    command: "which techs --format=list",
    answer: (
      <article className="qn_answer">
        <h4>Just Listing my favourites here :D</h4>
        <ul>
          <li>Next.js</li>
          <li>TypeScript</li>
          <li>TailwindCSS</li>
          <li>PostgreSQl</li>
          <li>Go</li>
        </ul>
        ---
        <ul>
          <li>VSCode (IDE)</li>
          <li>GitHub (Hosting)</li>
          <li>Pieces (AI Helper)</li>
          <li>Bruno (API Testing)</li>
          <li>Figma (UI Design)</li>
          <li>Brave (Browser)</li>
          <li>Obsidian (Notes)</li>
        </ul>
      </article>
    ),
  },
  {
    question: "Which Operating System do I use?",
    command: "which os",
    answer: (
      <article className="qn_answer">
        <p>I use Windows 11 for gaming &gt;&lt;</p>
        <p>
          And <span>Debian based</span> distro (mainly Zorin OS) for everything
          else :D
        </p>

        <p>My fav distro till now are - </p>

        <ul>
          <li>
            <span>Zorin OS</span>
          </li>
          <li>
            <span>Deepin OS</span>
          </li>
          <li>
            <span>Kali</span>
          </li>
          <li>
            <span>Archcraft</span>
          </li>
          <li>
            <span>Garuda Linux</span>
          </li>
        </ul>
      </article>
    ),
  },
  {
    question: "Favorite websites?",
    command: "cat web.txt | tail -n 10",
    answer: (
      <article className="qn_answer">
        <ul style={{ marginTop: "1rem" }}>
          <li>
            <a target="_blank" rel="noreferrer" href="https://quickref.me">
              QuickRef
            </a>
            - A Quick cheetsheet for me
          </li>
          <li>
            <a target="_blank" rel="noreferrer" href="https://nextjs.org/docs">
              Vercel Docs
            </a>
            - The Book for Next.js
          </li>
          <li>
            <a target="_blank" rel="noreferrer" href="https://duck.ai">
              Duck AI
            </a>{" "}
            - For quick private answers
          </li>
          <li>
            <a target="_blank" rel="noreferrer" href="https://linkedin.com">
              LinkedIn
            </a>{" "}
            - To connect great minds
          </li>
          <li>
            <a target="_blank" rel="noreferrer" href="https://leetcode.com">
              LeetCode
            </a>
            - To get better everyday
          </li>
          <li>
            <a target="_blank" rel="noreferrer" href="https://youtube.com">
              YouTube
            </a>{" "}
            - To watch great content
          </li>
          <li>
            <a href="https://x.com">X (Twitter)</a> - To be find Similar minds
          </li>
          <li>
            <a href="https://github.com">GitHub</a> - To explore open source
            planet
          </li>
        </ul>
      </article>
    ),
  },
  {
    question: "Hobbies?",
    command: "what hobbies",
    answer: (
      <article className="qn_answer">
        <p>
          Not gonna lie, I don&apos;t like <span>reading books</span>.
        </p>
        <p>
          Whenever I&apos;m bored, I either go for <span>YouTube</span> or{" "}
          <span>movies</span> or play <span>games</span> :D
        </p>
        <p>
          Oh, and I also like to play with <span>wires</span> and{" "}
          <span>electricity</span>, though I am not an electric guy &gt;&lt;
        </p>
      </article>
    ),
  },
  {
    question: "Learning Stack?",
    command: "ls -laR /upcoming --format=list",
    answer: (
      <article className="qn_answer">
        <ul>
          <li>Web3</li>
          <li>Cryptography</li>
          <li>GraphQL</li>
          <li>RabbitMQ</li>
          <li>Rust</li>
          <li>Microservices</li>
          <li>Webassembly</li>
          <li>Flutter</li>
        </ul>
      </article>
    ),
  },
  {
    question: "Favorite books?",
    command: "which books",
    answer: (
      <article className="qn_answer">
        <p>As I said, I don&apos;t like reading books :D</p>
        <p>
          But, I do love reading PDFs about some cryspy stuff. Like -
          <span>Blockchain</span>, <span>Cryptography</span>,{" "}
          <span>Algorithms</span>, <span>New Technologies</span>. And sometimes{" "}
          <span>Interview questions</span> :)
        </p>
      </article>
    ),
  },
  // {
  //   question: "Favorite movies?",
  //   command: "which movies",
  //   answer: (
  //     <article className="qn_answer">
  //       <p>I love watching movies about adventure, romance, and comedy.</p>
  //     </article>
  //   ),
  // },
  {
    question: "Favorite quotes/lines?",
    command: "cat quotes.txt | tail -n 13",
    answer: (
      <article className="quotes">
        <ul>
          <li>
            The game is mine, nobody do it better.{" "}
            <a href="https://www.youtube.com/watch?v=YDHguiBuFsA">- Source</a>
          </li>
          <li>
            Don&apos;t let anyone tell ya what you should do.{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            Just keep pushing through, cuz what u got to lose ?{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            Nobody stopping me except for me now.{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            Cause you have only one life, one chance to do it.{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            One day you&apos;ll look back so glad you pursued it.{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            I won&apos;t give up, I won&apos;t back down.{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            We take action with passion, we&apos;re rocking now.{" "}
            <a href="https://www.youtube.com/watch?v=FHW7rIRQl38">- Source</a>
          </li>
          <li>
            I feel right and I&apos;m proud, hype and I&apos;m loud.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
          <li>
            I&apos;m alone in a croud, I won&apos;t feel down.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
          <li>
            Keep your head high, even when you are down inside.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
          <li>
            Nothing is in your way but yourself.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
          <li>
            You need nobody&apos;s help, you can make it through this hell.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
          <li>
            This life is a prison if you don&apos;t have vision.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
          <li>
            Be something somehow, don&apos;t let yourself down.{" "}
            <a href="https://www.youtube.com/watch?v=TXcg25C56xM">- Source</a>
          </li>
        </ul>
      </article>
    ),
  },
];
