import type { ReactNode } from "react";

import "@/styles/questions.css";

/**
 * Terminal commands.
 * @type {object} questions as string and answers as React.ReactNode.
 */
export const questions: {
  question: string;
  command: string;
  answer: ReactNode;
}[] = [
  {
    question: "Who/What is Xron Trix?!",
    command: "whois xrontrix --verbose",
    answer: (
      <article className="qn_answer">
        <p>
          You probably guessed it! It&apos;s not my real name. I always wanted
          to name myself something unique :)
        </p>
        <p>
          I loved the series <span>Ben 10</span> from Cartoon Network. So, the{" "}
          <span>&quot;Trix&quot;</span> was taken from the watch name
          &quot;Omnitrix&quot;.
        </p>
        <p>
          Then <span>&quot;Xron&quot;</span> was added to the front to make it
          sound more unique, generated by my brain.
        </p>
        <p>Though &quot;X&quot; was inspired by Elon Musk :D</p>
      </article>
    ),
  },
  {
    question: "What I actually do?",
    command: "man xrontrix",
    answer: (
      <article className="qn_answer">
        <p>I actually do a lot more than a &quot;front-end developer&quot;.</p>
        <p>
          I was more interested and curious in <span>backends</span>,{" "}
          <span>cloud</span> and logic building. But suddenly I also became good
          at frontend development. So, I landed my <span>first job</span> as a
          front-end developer.
        </p>
        <p>
          Along with frontend, I have worked on multiple backends and full-stack
          applications. Most of them are in <span>NodeJs</span>,{" "}
          <span>MongoDB</span> or <span>SQL</span>.
        </p>
        <p>
          But, my favourite backend stack is <span>Go</span> with{" "}
          <span>PostgreSQl</span>. For frontend, I use <span>Next.js</span>,{" "}
          <span>TypeScript</span> and <span>TailwindCSS</span>
        </p>
        <p>
          Btw, this portfolio is built with Next.js and TailwindCSS, it&apos;s
          using <span>Cloudflare serverless Pages</span> and{" "}
          <span>KV database</span> :D
        </p>
      </article>
    ),
  },
  {
    question: "Skills? Experience?",
    command: "info xrontrix --format=table",
    answer: (
      <article className="qn_answer">
        {/* Basics table */}
        <h4>Basics</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>HTML, CSS</td>
              <td>5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Bash</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Git</td>
              <td>3.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>C, C++, Python</td>
              <td>5 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        {/* Front-end table */}
        <h4>Front-end</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>JavaScript (ES6+)</td>
              <td>4 Yr+ Experience</td>
            </tr>
            <tr>
              <td>React</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Next.js</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>TypeScript</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>TailwindCSS</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        {/* Back-end table */}
        <h4>Back-end</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>NodeJs</td>
              <td>3 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Go</td>
              <td>1 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Cloudflare Workers</td>
              <td>3 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        <h4>Database</h4>

        <table>
          <thead>
            <tr>
              <th>Technology</th>
              <th>Experience</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>PostgreSQL</td>
              <td>2 Yr+ Experience</td>
            </tr>
            <tr>
              <td>MongoDB</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>SQL</td>
              <td>2.5 Yr+ Experience</td>
            </tr>
            <tr>
              <td>Cloudflare KV, D1 (SQLite)</td>
              <td>2 Yr+ Experience</td>
            </tr>
          </tbody>
        </table>

        {/* Other table */}
        <h4>Other Essentials</h4>

        <table>
          <thead>
            <tr>
              <th>Skill</th>
              <th>Progress</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Data structure & Algorithms</td>
              <td>Leetcode 80+ Solutions</td>
            </tr>
            <tr>
              <td>Computer Network</td>
              <td>Intermediate</td>
            </tr>
            <tr>
              <td>Linux</td>
              <td>Debian, Arch (3+ Yr+ Experience)</td>
            </tr>
            <tr>
              <td>Cryptography, Encryption</td>
              <td>In Progress</td>
            </tr>
            <tr>
              <td>DevOps</td>
              <td>In Progress</td>
            </tr>
          </tbody>
        </table>
      </article>
    ),
  },
  {
    question: "Where I'm from?",
    command: "whereis xrontrix",
    answer: (
      <article className="qn_answer">
        <p>
          XronTrix is from{" "}
          <a
            rel="noreferrer"
            target="_blank"
            href="https://ben10.fandom.com/wiki/Galvan_Prime_(Classic)"
          >
            Galvan Prime
          </a>
          . He was created by{" "}
          <a
            rel="noreferrer"
            target="_blank"
            href="https://ben10.fandom.com/wiki/Azmuth_(Classic)"
          >
            Azmuth
          </a>
          .
        </p>
        <p>
          He is an advanced humanoid with a unique ability to teleport. He
          travels the galaxy in search of new worlds to explore.
        </p>

        <p>Just Kidding :D</p>
      </article>
    ),
  },
  {
    question: "What is my current role?",
    command: "which role",
    answer: (
      <article>
        I&apos;m a front-end developer with a passion for developing full-stack
        applications.
      </article>
    ),
  },
  {
    question: "Strengths and weaknesses?",
    command: "describe --strengths --weakness",
    answer: (
      <div>
        My strengths include my ability to develop full-stack applications and
        my passion for front-end development.
      </div>
    ),
  },
  {
    question: "Favorite technologies?",
    command: "which techs",
    answer: (
      <div>
        I&apos;m a front-end developer with a passion for developing full-stack
        applications.
      </div>
    ),
  },
  {
    question: "Which Operating System do I use?",
    command: "which os",
    answer: <div>I use Windows 10.</div>,
  },
  {
    question: "Favorite tools?",
    command: "ls /tools | head -n 10",
    answer: <div>I use Visual Studio Code as my primary code editor.</div>,
  },
  {
    question: "Favorite websites?",
    command: "cat web.txt | tail -n 10",
    answer: <div>I love to browse websites and learn new things.</div>,
  },
  {
    question: "Hobbies?",
    command: "what hobbies",
    answer: <div>I love to read books and watch movies.</div>,
  },
  {
    question: "Favorite books?",
    command: "which books",
    answer: (
      <div>I love reading books about history, philosophy, and science.</div>
    ),
  },
  {
    question: "Favorite movies?",
    command: "which movies",
    answer: (
      <div>I love watching movies about adventure, romance, and comedy.</div>
    ),
  },
  {
    question: "What is my favorite quote?",
    command: "cat quotes.txt | tail -n 1",
    answer: (
      <div>
        &quot;The best way to predict the future is to invent it.&quot; - Alan
        Kay
      </div>
    ),
  },
];
