import type { JSX } from "react";

/**
 * answers/whois-xrontrix component.
 * @returns {JSX.Element} the component.
 */
const WhoisXrontrix = (): JSX.Element => {
  return (
    <article className="qn_answer">
      <p>
        You probably guessed it! It&apos;s not my real name. I always wanted to
        name myself something unique :)
      </p>
      <p>
        I loved the series <span>Ben 10</span> from Cartoon Network. So, the{" "}
        <span>&quot;Trix&quot;</span> was taken from the watch name
        &quot;Omnitrix&quot;.
      </p>
      <p>
        Then <span>&quot;Xron&quot;</span> was added to the front to make it
        sound more unique, generated by my brain.
      </p>
      <p>Though &quot;X&quot; was inspired by Elon Musk :D</p>
    </article>
  );
};

export default WhoisXrontrix;
